[package]
name = "rusteze-common"
version = "0.1.0"
description = "Common library for Rusteze."
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}


