service_name = "auth-example"

[deployment]
provider = "aws"
region = "ap-southeast-2"
# optional - By default it will use this.
type = "lambda"


# optional depending on deployment
[lambda]
memory_size = 256